#!/usr/bin/env python3
"""
Capacity plan from the live data: how fast PayFlow grows, what that means for
disk and memory in 12 and 24 months.

    .venv/bin/python tuning/capacity.py > docs/evidence/phase4/capacity.md

Method
  * monthly transaction volume over the last 12 full months, with a
    least-squares linear trend extrapolated forward
  * on-disk bytes per row (data + indexes) per table, measured
  * ledger lines grow with transactions (measured ratio); other tables are
    small and grow with customers, so they're included at measured size
  * the "hot" working set for the buffer pool = the last 90 days of
    transactions and ledger lines (what statements, reports and checks touch)
"""

import os
import sys

import mysql.connector

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from loadgen import read_env  # noqa: E402

AS_OF = "2026-09-30"


def main():
    env = read_env()
    conn = mysql.connector.connect(host="127.0.0.1", port=3306, user="payflow_bench" if os.path.exists(os.path.join(ROOT, ".private/security-enabled")) else "root",
                                   password=env.get("BENCH_PASSWORD" if os.path.exists(os.path.join(ROOT, ".private/security-enabled")) else "MYSQL_ROOT_PASSWORD", ""), database="payflow",
                                   ssl_ca=os.path.join(ROOT, ".private/tls/ca.pem"), ssl_verify_cert=True, ssl_verify_identity=True)
    cur = conn.cursor()

    # make capacity refreshes statistics through the local administrator socket.
    cur.execute("""SELECT table_name, table_rows, data_length + index_length
                     FROM information_schema.tables WHERE table_schema = 'payflow'""")
    tables = {name: (rows, size) for name, rows, size in cur.fetchall()}
    cur.execute("SELECT COUNT(*) FROM transactions")
    txn_rows = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM ledger_entries")
    ledger_rows = cur.fetchone()[0]
    txn_bytes = tables["transactions"][1] / txn_rows
    ledger_bytes = tables["ledger_entries"][1] / ledger_rows
    lines_per_txn = ledger_rows / txn_rows
    other = sum(size for name, (rows, size) in tables.items() if name not in ("transactions", "ledger_entries"))
    total_now = sum(size for _, size in tables.values())

    # the last 12 *full* months (September 2026 is one day short in the data)
    cur.execute("""SELECT DATE_FORMAT(created_at, '%Y-%m') m, COUNT(*) FROM transactions
                    WHERE created_at >= '2025-09-01' AND created_at < '2026-09-01'
                    GROUP BY m ORDER BY m""")
    months = cur.fetchall()
    cur.execute(f"SELECT COUNT(*) FROM transactions WHERE created_at >= '{AS_OF}' - INTERVAL 90 DAY "
                f"AND created_at < '{AS_OF}'")
    txn_90d = cur.fetchone()[0]

    # least-squares line through the monthly counts
    ys = [n for _, n in months]
    xs = list(range(len(ys)))
    xbar, ybar = sum(xs) / len(xs), sum(ys) / len(ys)
    slope = sum((x - xbar) * (y - ybar) for x, y in zip(xs, ys)) / sum((x - xbar) ** 2 for x in xs)
    intercept = ybar - slope * xbar
    monthly = lambda k: intercept + slope * (len(ys) - 1 + k)   # k months after the last full month

    gb = lambda b: b / 1024 ** 3
    print("# Capacity plan (generated by tuning/capacity.py)\n")
    print(f"Data as of {AS_OF}. Measured on-disk cost: **{txn_bytes:,.0f} B per transaction** "
          f"(data + 9 indexes) and **{ledger_bytes:,.0f} B per ledger line**; "
          f"{lines_per_txn:.2f} ledger lines per transaction, so each transaction costs "
          f"**{txn_bytes + lines_per_txn * ledger_bytes:,.0f} B** in total.\n")
    print("| Month | Transactions |\n|---|---|")
    for m, n in months:
        print(f"| {m} | {n:,} |")
    growth = slope / ybar * 100
    print(f"\nTrend: **+{slope:,.0f} transactions/month each month** (~{growth:.1f}% of the average month).\n")

    per_txn = txn_bytes + lines_per_txn * ledger_bytes
    print("| Horizon | Transactions/month | Total transactions | Database size | Hot 90-day working set |")
    print("|---|---|---|---|---|")
    total_txn = txn_rows
    print(f"| now | {ys[-1]:,} | {txn_rows:,} | {gb(total_now):.1f} GB | "
          f"{gb(txn_90d * per_txn):.1f} GB |")
    for horizon in (12, 24):
        added = sum(monthly(k) for k in range(1, horizon + 1))
        last3 = sum(monthly(k) for k in range(horizon - 2, horizon + 1))
        size = gb(other + (total_txn + added) * per_txn)
        print(f"| +{horizon} months | {monthly(horizon):,.0f} | {total_txn + added:,.0f} | "
              f"{size:.1f} GB | {gb(last3 * per_txn):.1f} GB |")
    print("\nBinary logs (7 days kept), backups (2 full + 3 logical) and the binlog archive come on top: "
          "budget roughly 3x the database size for the volume holding data and backups.")
    conn.close()


if __name__ == "__main__":
    main()
